/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.autotrade.zxtradesdk;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ZX_TRADE_ERROR_CODE implements org.apache.thrift.TEnum {
  ZX_TRADE_OK(0),
  ZX_TRADE_LOAD_CONFIG_FILE_ERROR(1),
  ZX_TRADE_INIT_CONN_HANDLE_ERROR(2),
  ZX_TRADE_CONN_SERVER_ERROR(3),
  ZX_TRADE_ACCOUNT_LOGIN_ERROR(4),
  ZX_TRADE_SEARCH_STOCKHOLDER_ERROR(5),
  ZX_TRADE_SEARCH_FUND_MSG_ERROR(6),
  ZX_TRADE_RUN_NORMAL_ENTRUST_ERROR(7),
  ZX_TRADE_SERACH_ENTRUST_STATUS_ERROR(8),
  ZX_TRADE_RUN_UNDO_ENTRUST_ERROR(9),
  ZX_TRADE_ACCOUNT_PWD_ERROR(21),
  ZX_TRADE_OBJ_NOT_FIND_ERROR(22),
  ZX_TRADE_USE_EXCHANGE_TYPE_NOT_FIND_ACCOUNT_ERROR(23);

  private final int value;

  private ZX_TRADE_ERROR_CODE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ZX_TRADE_ERROR_CODE findByValue(int value) { 
    switch (value) {
      case 0:
        return ZX_TRADE_OK;
      case 1:
        return ZX_TRADE_LOAD_CONFIG_FILE_ERROR;
      case 2:
        return ZX_TRADE_INIT_CONN_HANDLE_ERROR;
      case 3:
        return ZX_TRADE_CONN_SERVER_ERROR;
      case 4:
        return ZX_TRADE_ACCOUNT_LOGIN_ERROR;
      case 5:
        return ZX_TRADE_SEARCH_STOCKHOLDER_ERROR;
      case 6:
        return ZX_TRADE_SEARCH_FUND_MSG_ERROR;
      case 7:
        return ZX_TRADE_RUN_NORMAL_ENTRUST_ERROR;
      case 8:
        return ZX_TRADE_SERACH_ENTRUST_STATUS_ERROR;
      case 9:
        return ZX_TRADE_RUN_UNDO_ENTRUST_ERROR;
      case 21:
        return ZX_TRADE_ACCOUNT_PWD_ERROR;
      case 22:
        return ZX_TRADE_OBJ_NOT_FIND_ERROR;
      case 23:
        return ZX_TRADE_USE_EXCHANGE_TYPE_NOT_FIND_ACCOUNT_ERROR;
      default:
        return null;
    }
  }
}
